### ISSUE TITLE
Enhancement: SS4 support

### ISSUE THREAD

**Issue by robbieaverill** [brettt89/sspak-docker#1]
I've tweaked my docker-compose config to look like this:

```yaml
  sspak:
    image: brettt89/sspak
    links:
      - db:db
    volumes:
      - ./snapshots:/app/snapshots:ro
      - ./html/.env:/app/.env:ro
      - ./html:/app/public:ro
```

I get this result:

```
$ docker-compose run sspak load snapshots/snapshot.sspak /app/public
Starting cwp2docker_db_1 ... done
Command: /usr/bin/env 'php' '/tmp/sspak-sniffer-522599.php' '/app/public'
Execution failed: returned 2.
Output:
Couldn't locate framework's Core.php. Perhaps /app/public is not a SilverStripe project?
```

To be fair, I think this error might be caused by sspak itself. I get the same result when downloading and running sspak in my web box's Dockerfile too.
